### ISSUE TITLE
Better generated names.

### ISSUE THREAD

**Issue by ArjixWasTaken** [kroegerama/openapi-kgen#5]
My API methods are already fluently named, so the generated names suck.

Original API
![image](https://github.com/kroegerama/openapi-kgen/assets/53124886/58d7d8d7-460d-4374-8ff3-3951f824cf51)

Generated client:
`AuthApi.postApiAuthLogin`, `AuthApi.postApiAuthLogout`, `AuthApi.postApiAuthRefresh`

would be nicer is they were just named `AuthApi.Login`, `AuthApi.Logout`, `AuthApi.Refresh`

**Comment by ArjixWasTaken** [comment]
maybe add a naming template in the plugin params?
that way we can have whatever naming scheme we want

**Comment by kroegerama** [comment]
Hi there, thanks for the suggestion! Unfortunately, this feature would require a lot of rework. I use this generator for a lot of projects and am actually quite happy with the current state. But you are right, the auto-generated names are not really nice to read or use.

Can't you just use the `operationId` property for each operation in your spec? That's what we use in all our specs.

**Comment by ArjixWasTaken** [comment]
That is exactly what I needed!
Thank you so much!!

I am not really that knowledgeable about OpenAPI, it is auto generated by swagger for me, so I didn't know that was an option.
This issue has been resolved.

**Comment by ArjixWasTaken** [comment]
*Commenting here instead of opening a new issue since this ain't an issue*

On another note, the spacing of the generated code is odd
![image](https://github.com/kroegerama/openapi-kgen/assets/53124886/f65341c9-dfa5-4b44-bc3f-f14d71db0e4e)

**Comment by kroegerama** [comment]
Yeah, that's because of the library I use for the Kotlin code generation: [Kotlin Poet](https://square.github.io/kotlinpoet/).

You could run a code formatter on the generated code, if you care enough. Something like: [Ktlint](https://pinterest.github.io/ktlint/0.50.0/)
